---
ID: "0f3b65fb-fd6a-4a18-a58f-be8b69b33c70"
Parent: "63af0d30-913a-4d7a-a4db-7f530cd70129"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/TAC/Events/Presentation/Headless Variants/EventPromo/Default
BranchID: "98e50b7b-6fab-44e7-b8df-fd38eeecdb83"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{DA61F9C2-6C0B-4DEC-BB60-40A1038D4E38}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231222T165720Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\eastmondr@bennettjones.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\eastmondr@bennettjones.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "406c4b82-97bc-4fb7-8011-ed6d9312dcea"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\eastmondr@bennettjones.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231222T165720Z
